global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: prod

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  # Spring Boot 메트릭
  - job_name: 'spring-app'
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ['spring-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
