server:
  http_listen_port: 9080
clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker-logs
    pipeline_stages:
      - docker: {} # 도커 로그 JSON wrapper 제거
      - json:
          expressions:
            level: level
            logger: logger
            message: message
            traceId: traceId
            spanId: spanId
            path: path
            method: method
            status: status
      - labels:
          level:
          path:
          method:
          status:
    static_configs:
      - targets: [localhost]
        labels:
          job: spring-app
          # 컨테이너 로그 파일 경로들 (Docker on Linux 예시)
          __path__: /var/lib/docker/containers/*/*-json.log
